# This is a basic workflow to help you get started with Actions

name: PlatformIO CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.RC_PAT_TOKEN_ACTIONS_ONLY }}
        submodules: recursive 

    # Install Python
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
          python-version: '3.9'

    # Installing pip and platformIO
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        
    - name: Run PlatformIO
      run: |
        platformio run
